### ISSUE TITLE
User Count should be improved

### ISSUE THREAD

**Issue by vmitchell85** [AndreasElia/laravel-analytics#14]
As far as I can tell you're counting the number of users by Country.

https://github.com/AndreasElia/laravel-analytics/blob/0438e67b4dc5d4775e161a49ef3fc02ec92822c7/src/Http/Controllers/HomeController.php#L81-L88

Seems like maybe going by IP Address or, even better, the session would be preferred. The only catch with using the session is that the session id changes once the user is logged in.

**Comment by AndreasElia** [comment]
That is more for the user listing card, the stats are counted separately here:

https://github.com/AndreasElia/laravel-analytics/blob/0438e67b4dc5d4775e161a49ef3fc02ec92822c7/src/Http/Controllers/HomeController.php#L43-L60

**Comment by vmitchell85** [comment]
Ah, that makes more sense. I think I'd still prefer session or something else. Since multiple users at the same company or at a library would all track as single users using IP only. Everyone at GitHub could be using my app but it would only show one user.

**Comment by AndreasElia** [comment]
That's very true. I'll keep the issue open so I can work on a solution for this tomorrow.

**Comment by AndreasElia** [comment]
I believe this is now sorted @vmitchell85 😄
