### ISSUE TITLE
On a fresh install, group by function error is obtained

### ISSUE THREAD

**Issue by nachete1987** [AndreasElia/laravel-analytics#21]
I installed analytics componen via composer and executed the steps indicated in installation github guide and when I go to analytics page I'm obtaining this error:

`SQLSTATE[42000]: Syntax error or access violation: 1055 'page_views.id' isn't in GROUP BY (SQL: select * from `page_views` where date(`created_at`) = 2021-02-20 group by `session`)`

**Comment by nachete1987** [comment]
sorry, the solution was change strict mode in database.php config file to strict => false

**Comment by AndreasElia** [comment]
No worries, I'm happy you sorted it.

Take care.

**Comment by AndreasElia** [comment]
Reopening to apply a fix so the need to disable strict isn't required.

**Comment by AndreasElia** [comment]
@nachete1987 I have tagged a new release, v1.3.3, which should now allow you to keep strict enabled.
