### ISSUE TITLE
Queue tracking?

### ISSUE THREAD

**Issue by grantholle** [andreaselia/laravel-analytics#41]
Hi, not sure if you'd be open for PR's to queue page view tracking instead of doing it synchronously each request?

**Comment by andreaselia** [comment]
Hi @grantholle,

I'd be open to it so long as it's optional (off by default to maintain current functionality), and includes tests.

Thanks 👍

**Comment by grantholle** [comment]
Apparently request objects can't be serialized, so it's not really worth the effort to make a serialized version of the request... a nice thought I guess.
