### ISSUE TITLE
Use Dashboard UI without Nova?

### ISSUE THREAD

**Issue by chrissy-dev** [andreaselia/laravel-analytics#48]
Similar to #47 - I'm simply using blade on a very minimal project, how do I add a route for say `/analytics` and show the dashboard? 

I've tried calling the view directly but the data is missing.

**Comment by chrissy-dev** [comment]
Ahh got it. 

```
Route::get('/{view?}', 'HomeController@index')->where('view', '(.*)')->name('analytics');
```

**Comment by andreaselia** [comment]
Glad you figured it out, if you need anything just let us know.
