### ISSUE TITLE
session store not set on request

### ISSUE THREAD

**Issue by myneid** [andreaselia/laravel-analytics#63]
when i add it as a middleware in Kernel.php
protected $middleware = [
...
        \AndreasElia\Analytics\Http\Middleware\Analytics::class,
    ];

i get this error of "sessin store not set on request"

previously i had added this above calling analytics 
  //\Illuminate\Session\Middleware\StartSession::class,

but i guess this does not work with jetstream. it messes up the jetstream (fortify) sessions

i have not figured out how to do this. any suggestions?

**Comment by andreaselia** [comment]
Hmm, could be another issue with Jetstream. Could you create a minimum reproducible example with a brand new Laravel 11 and Jetstream install and see if it's still an issue?

**Comment by andreaselia** [comment]
Let us know if this is still an issue.
