### ISSUE TITLE
Error Detection\MobileDetect::setUserAgent() after updating to Laravel 11

### ISSUE THREAD

**Issue by buzkall** [andreaselia/laravel-analytics#64]
My log shows this error:

`TypeError · Detection\MobileDetect::setUserAgent(): Argument #1 ($userAgent) must be of type string, null given, called in vendor/andreaselia/analytics/src/Http/Middleware/Analytics.php on line 33
`

The request headers look like this:

```
{
  "cf-connecting-ip": "198.235.24.149",
  "cf-visitor": "{\"scheme\":\"https\"}",
  "x-forwarded-proto": "https",
  "cf-ray": "88dc5697cb9704aa-CDG",
  "x-forwarded-for": "198.235.24.149",
  "accept-encoding": "gzip, br",
  "cf-ipcountry": "US",
  "cdn-loop": "cloudflare",
}
```

**Comment by andreaselia** [comment]
@buzkall what version of the package are you on?

**Comment by andreaselia** [comment]
We have a version 2 out if you're not already on it.

**Comment by buzkall** [comment]
Yes, I'm using version 2

**Comment by andreaselia** [comment]
@tomirons any other questions in mind to help debug this?

Line 33 in the package for that file is a blank line.

**Comment by andreaselia** [comment]
There's only one version 2 I think, but might be worth verifying what's in your composer.json file @buzkall.

**Comment by andreaselia** [comment]
@buzkall can you try v2.1.0 and let us know how you get on please? Thank you!
