### ISSUE TITLE
Excluded Routes with query strings are still tracked

### ISSUE THREAD

**Issue by vmitchell85** [AndreasElia/laravel-analytics#9]
Even with the default configuration historical `/analytics` pages are shown in the data:

![image](https://user-images.githubusercontent.com/1248035/107862963-87b82a80-6e1e-11eb-8ab9-4c1f5bf853ea.png)

I presume if I choose to ignore `/analytics` that should cover the page with or without query parameters

**Comment by AndreasElia** [comment]
That's correct @vmitchell85.

It seems to be an issue with the way I handle the whitelist. I'll check it out - thanks for letting me know.

**Comment by vmitchell85** [comment]
I think if you update the following with `@request->url()` instead of `$request->fullUrl()` it might fix it

https://github.com/AndreasElia/laravel-analytics/blob/4eb11679365fe4393e907f2df6cbc9f70070527e/src/Http/Middleware/Analytics.php#L12-L16

**Comment by vmitchell85** [comment]
Testing locally confirms it has fixed it, though I'm not sure if you had another reason for `fullUrl()`

**Comment by AndreasElia** [comment]
I don't believe there was a reason for using `fullUrl` over just `url` so I've updated it and will tag a new release shortly. I'm just going to remove the install command quickly and then I'll tag it.

**Comment by AndreasElia** [comment]
Thanks again for reporting as well as the solution 👍

**Comment by AndreasElia** [comment]
New version released now @vmitchell85.

If you have any issues or requests, feel free to add a new issue and I'll work on them as soon as I can.

Take care and stay safe.
